apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: issue-aggregator
  name: issue-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: issue-aggregator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: issue-aggregator
    spec:
      containers:
        - env:
            - name: DATABASE_URL
            - name: GITHUB_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: GITHUB_TOKEN
                  name: issue-aggregator-env
            - name: ISSUE_DB_URL
              valueFrom:
                configMapKeyRef:
                  key: ISSUE_DB_URL
                  name: issue-aggregator-env
            - name: TEST_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: TEST_DATABASE_URL
                  name: issue-aggregator-env
          image: misstipo/docker-issue-aggregator
          name: issue-aggregator
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
