apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-management
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-management
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-management
    spec:
      containers:
        - env:
            - name: DATABASE_URL
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: GITHUB_CLIENT_ID
                  name: user-management-env
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: GITHUB_CLIENT_SECRET
                  name: user-management-env
            - name: GITHUB_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: GITHUB_TOKEN
                  name: user-management-env
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET_KEY
                  name: user-management-env
            - name: TEST_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: TEST_DATABASE_URL
                  name: user-management-env
            - name: TOKEN_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: TOKEN_EXPIRATION
                  name: user-management-env
            - name: USER_DB_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_DB_URL
                  name: user-management-env
          image: misstipo/docker-user-management
          name: user-management
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
