"""Define a JSON Column Type

Revision ID: 38ebd21aaa82
Revises: 3b094f85f8b3
Create Date: 2025-02-26 08:25:48.166648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ebd21aaa82'
down_revision: Union[str, None] = '3b094f85f8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'labels',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='labels::jsonb',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'labels',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON(),
               postgresql_using='labels::json',
               existing_nullable=True)
    # ### end Alembic commands ###
