"""Enable PostgreSQL’s JSON containment operator (@>)

Revision ID: 615886daeb1e
Revises: 38ebd21aaa82
Create Date: 2025-02-26 08:56:05.704034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615886daeb1e'
down_revision: Union[str, None] = '38ebd21aaa82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
