"""Initial migration

Revision ID: 7bf8c6e62ed5
Revises: 
Create Date: 2025-02-21 11:40:49.004720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf8c6e62ed5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('external_id', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('created_at', sa.String(length=50), nullable=True))
    op.add_column('issues', sa.Column('updated_at', sa.String(length=50), nullable=True))
    op.add_column('issues', sa.Column('url', sa.String(length=100), nullable=True))
    op.add_column('issues', sa.Column('labels', sa.String(length=50), nullable=True))
    op.add_column('issues', sa.Column('repository_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'repository_id')
    op.drop_column('issues', 'labels')
    op.drop_column('issues', 'url')
    op.drop_column('issues', 'updated_at')
    op.drop_column('issues', 'created_at')
    op.drop_column('issues', 'external_id')
    # ### end Alembic commands ###
