"""Enable PostgreSQL’s JSON containment operator (@>)

Revision ID: e85e38458927
Revises: 615886daeb1e
Create Date: 2025-02-26 08:59:34.184092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85e38458927'
down_revision: Union[str, None] = '615886daeb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
