"""Initial migration

Revision ID: ede7b81a2c7e
Revises: 7bf8c6e62ed5
Create Date: 2025-02-21 11:44:21.452097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede7b81a2c7e'
down_revision: Union[str, None] = '7bf8c6e62ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
